-- ---------------------------------------------------------
-- 1. members 데이터 삽입 (ID 1~40)
-- ---------------------------------------------------------
INSERT IGNORE INTO members (created_at, updated_at, email, member_name, password, phone, provider, provider_id, role, status)
VALUES (NOW(), NOW(), 'manager1@test.com', '성수매니저', 'password', '010-1111-1111', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'manager2@test.com', '강남매니저', 'password', '010-2222-2222', 'NORMAL', NULL, 'STORE_MANAGER','ACTIVE'),
       (NOW(), NOW(), 'manager3@test.com', '연남매니저', 'password', '010-3333-3333', 'NORMAL', NULL, 'STORE_MANAGER','ACTIVE'),
       (NOW(), NOW(), 'manager4@test.com', '이태원매니저', 'password', '010-4444-4444', 'NORMAL', NULL, 'STORE_MANAGER','ACTIVE'),
       (NOW(), NOW(), 'manager5@test.com', '판교매니저', 'password', '010-5555-5555', 'NORMAL', NULL, 'STORE_MANAGER','ACTIVE'),
       (NOW(), NOW(), 'm6@test.com', '건대매니저', 'pass', '010-0006', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm7@test.com', '왕십리매니저', 'pass', '010-0007', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm8@test.com', '잠실매니저', 'pass', '010-0008', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm9@test.com', '서울숲매니저', 'pass', '010-0009', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm10@test.com', '한양대매니저', 'pass', '010-0010', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm11@test.com', '압구정매니저', 'pass', '010-0011', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm12@test.com', '논현매니저', 'pass', '010-0012', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm13@test.com', '청담매니저', 'pass', '010-0013', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm14@test.com', '천호매니저', 'pass', '010-0014', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm15@test.com', '군자매니저', 'pass', '010-0015', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm16@test.com', '뚝섬매니저', 'pass', '010-0016', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm17@test.com', '자양매니저', 'pass', '010-0017', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm18@test.com', '구의매니저', 'pass', '010-0018', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm19@test.com', '화양매니저', 'pass', '010-0019', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm20@test.com', '마장매니저', 'pass', '010-0020', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm21@test.com', '장안매니저', 'pass', '010-0021', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm22@test.com', '삼성매니저', 'pass', '010-0022', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm23@test.com', '회기매니저', 'pass', '010-0023', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm24@test.com', '가락매니저', 'pass', '010-0024', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm25@test.com', '대치매니저', 'pass', '010-0025', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm26@test.com', '역곡매니저', 'pass', '010-0026', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm27@test.com', '소사매니저', 'pass', '010-0027', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm28@test.com', '온수매니저', 'pass', '010-0028', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm29@test.com', '부천종합매니저', 'pass', '010-0029', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm30@test.com', '궁동매니저', 'pass', '010-0030', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm31@test.com', '범박매니저', 'pass', '010-0031', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm32@test.com', '개봉매니저', 'pass', '010-0032', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm33@test.com', '천왕매니저', 'pass', '010-0033', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm34@test.com', '중동매니저', 'pass', '010-0034', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm35@test.com', '광명사거리매니저', 'pass', '010-0035', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm36@test.com', '오류매니저', 'pass', '010-0036', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm37@test.com', '고척매니저', 'pass', '010-0037', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm38@test.com', '철산매니저', 'pass', '010-0038', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm39@test.com', '옥길매니저', 'pass', '010-0039', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE'),
       (NOW(), NOW(), 'm40@test.com', '부천시청매니저', 'pass', '010-0040', 'NORMAL', NULL, 'STORE_MANAGER', 'ACTIVE');

-- ---------------------------------------------------------
-- 2. store_managers 데이터 삽입 (member_id와 1:1 매칭)
-- ---------------------------------------------------------
INSERT INTO store_managers (created_at, member_id, updated_at, verified_at, business_license_number)
VALUES (NOW(), 1, NOW(), NOW(), '111-81-12345'),
       (NOW(), 2, NOW(), NOW(), '222-82-23456'),
       (NOW(), 3, NOW(), NOW(), '333-83-34567'),
       (NOW(), 4, NOW(), NOW(), '444-84-45678'),
       (NOW(), 5, NOW(), NOW(), '555-85-56789'),
       (NOW(), 6, NOW(), NOW(), '666-06'),
       (NOW(), 7, NOW(), NOW(), '777-07'),
       (NOW(), 8, NOW(), NOW(), '888-08'),
       (NOW(), 9, NOW(), NOW(), '999-09'),
       (NOW(), 10, NOW(), NOW(), '000-10'),
       (NOW(), 11, NOW(), NOW(), '111-11'),
       (NOW(), 12, NOW(), NOW(), '222-12'),
       (NOW(), 13, NOW(), NOW(), '333-13'),
       (NOW(), 14, NOW(), NOW(), '444-14'),
       (NOW(), 15, NOW(), NOW(), '555-15'),
       (NOW(), 16, NOW(), NOW(), '160-16'),
       (NOW(), 17, NOW(), NOW(), '170-17'),
       (NOW(), 18, NOW(), NOW(), '180-18'),
       (NOW(), 19, NOW(), NOW(), '190-19'),
       (NOW(), 20, NOW(), NOW(), '200-20'),
       (NOW(), 21, NOW(), NOW(), '210-21'),
       (NOW(), 22, NOW(), NOW(), '220-22'),
       (NOW(), 23, NOW(), NOW(), '230-23'),
       (NOW(), 24, NOW(), NOW(), '240-24'),
       (NOW(), 25, NOW(), NOW(), '250-25'),
       (NOW(), 26, NOW(), NOW(), '260-26'),
       (NOW(), 27, NOW(), NOW(), '270-27'),
       (NOW(), 28, NOW(), NOW(), '280-28'),
       (NOW(), 29, NOW(), NOW(), '290-29'),
       (NOW(), 30, NOW(), NOW(), '300-30'),
       (NOW(), 31, NOW(), NOW(), '310-31'),
       (NOW(), 32, NOW(), NOW(), '320-32'),
       (NOW(), 33, NOW(), NOW(), '330-33'),
       (NOW(), 34, NOW(), NOW(), '340-34'),
       (NOW(), 35, NOW(), NOW(), '350-35'),
       (NOW(), 36, NOW(), NOW(), '360-36'),
       (NOW(), 37, NOW(), NOW(), '370-37'),
       (NOW(), 38, NOW(), NOW(), '380-38'),
       (NOW(), 39, NOW(), NOW(), '390-39'),
       (NOW(), 40, NOW(), NOW(), '400-40');

